server:
  port: 28070
spring:
  application:
    name: software
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
#    url: jdbc:mysql://10.66.1.192:3306/clouddemo?characterEncoding=utf-8&useSSL=false&useAffectedRows=true
    url: jdbc:mysql://10.66.1.204:3306/monitordb?characterEncoding=utf-8&useSSL=false&useAffectedRows=true
#  jpa:
#    show-sql: true
#  cloud:
#    config:
#      discovery:
#        enabled: true
#        service-id: CONFIG
#      profile: dev
eureka:
  client:
    service-url:
#      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/
#      defaultZone: http://10.66.1.202:8761/eureka-0.0.1-SNAPSHOT/eureka/,http://10.66.1.203:8761/eureka-0.0.1-SNAPSHOT/eureka/
      defaultZone: http://10.66.1.192:8761/eureka-0.0.1-SNAPSHOT/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
#SOFTWARE:
ribbon:
  NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
  ReadTimeout: 120000
  ConnectTimeout: 30000
mybatis:
  mapper-locations: classpath:mapping/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: com.ucd.server.model.*  # 注意：对应实体类的路径
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #打印SQL

basicparameters:
  transwarp:
    serviceinfourla: http://10.28.3.50:8180/api
    joburla: http://10.28.3.50:4044/api
    centrea: A
    usernamea: gongweimin
    passworda: gongweimin
    jobsizea: 6
    serviceinfourlb: http://10.28.3.51:8180/api
    joburlb: http://10.28.3.52:4044/api
    centreb: B
    usernameb: gongweimin
    passwordb: gongweimin
    jobsizeb: 3
    kafkatime: 0.01
  configrunning: 0
  centrelocal: A
  urlotherside: http://10.66.1.160:28070

