server:
  port: 28070
spring:
  application:
    name: software
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
#    url: jdbc:mysql://10.66.1.192:3306/clouddemo?characterEncoding=utf-8&useSSL=false&useAffectedRows=true
    url: jdbc:mysql://10.28.3.203:3306/monitordb?characterEncoding=utf-8&useSSL=false&useAffectedRows=true
#  jpa:
#    show-sql: true
#  cloud:
#    config:
#      discovery:
#        enabled: true
#        service-id: CONFIG
#      profile: dev
eureka:
  client:
    service-url:
#      defaultZone: http://localhost:8761/eureka/
       defaultZone: http://192.168.1.202:8761/eureka-0.0.1-SNAPSHOT/eureka/,http://192.168.1.203:8761/eureka-0.0.1-SNAPSHOT/eureka/
#      defaultZone: http://10.66.1.160:8761/eureka-0.0.1-SNAPSHOT/eureka/
  instance:
    ip-address: 192.168.1.202
    prefer-ip-address: true
    instance-id: 192.168.1.202:${server.port}
#SOFTWARE:
ribbon:
  NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
  ReadTimeout: 120000
  ConnectTimeout: 30000
mybatis:
  mapper-locations: classpath:mapping/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: com.ucd.server.model.*  # 注意：对应实体类的路径
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #打印SQL

basicparameters:
  transwarp:
    serviceinfourla: http://10.28.3.160:8180/api
    joburla: http://10.28.3.50:4044/api
    centrea: A
    usernamea: gongweimin
    passworda: gongweimin
    jobsizea: 13
    serviceinfourlb: http://10.28.3.51:8180/api
    joburlb: http://10.28.3.52:4044/api
    centreb: B
    usernameb: gongweimin
    passwordb: gongweimin
    jobsizeb: 3
    kafkatime: 1
    namenuma: 18
    namenumb: 20
    service-runtime: 180
    service-name-a: TOS,Transwarp_License_Cluster,ZooKeeper1,HDFS1,YARN1,Search1,Hyperbase1,TxSQL1,Inceptor1,Kafka1,Milano1,Slipstream1,Guardian,SlipstreamStudio1,Discover1,Workflow1,Inceptor2,Manager
    service-name-b: TOS,Transwarp_License_Cluster,ZooKeeper1,Kafka1,Search1,Milano1,HDFS1,YARN1,TxSQL1,Inceptor1,Slipstream1,Hyperbase1,Pilot1,Transporter1,Workflow1,Notification1,Rubik1,TxSQL2,Inceptor2,Manager
    #注意：与星环确认token和限制IP
    guardian-access-token: rrZs53w3ImiEjhLzpOqv-TDH
    syncip: 10.28.3.48
    syncusername: root
    syncpassword: bjcj@123456
    syncstartshell: /root/datasync/sync.sh
    syncstopshell: /root/datasync/yarnkiller.sh

  configrunning: 0
  centrelocal: B
  urlotherside: http://10.66.1.192:28070
